/*
  Rewrite `return a` to `{__urlCheck(a); return a}` so that box-js can
  potentially track URLs returned from string decode
  functions/methods.
 */
module.exports = (expr) => ({
    autogenerated: true,
    type: "BlockStatement",
    body: [
        {
            type: "ExpressionStatement",
            expression: {
                type: "CallExpression",
                callee: {
                    type: "Identifier",
                    "name": "__urlCheck"
                },
                arguments: [expr.argument],
            },
        },
        expr
    ],
});
